#!/bin/sh
x86_64-w64-mingw32-gcc -o pixper.exe main.c lib/sqlite3.c -I/usr/x86_64-w64-mingw32/include -I./lib -lraylib -lopengl32 -lgdi32 -lwinmm -L./lib -static-libgcc -static-libstdc++ -static
wine pixper.exe
